research_task:
  description: >
    You are given two research papers as knowledge sources. Carefully read both texts and extract key information from each, including:
    - Abstract and main objectives
    - Research methodologies
    - Key findings and results
    - Conclusions
    - All cited references (with author names and years)

    Then, align the information by:
    - Highlighting shared themes and overlapping findings
    - Identifying differences in methods or conclusions
    - Structuring your output into a clear and organized summary for further analysis

    Your goal is to prepare a comprehensive, structured alignment that can be easily reviewed by another agent.
  
  expected_output: >
    A well-structured summary in markdown or bullet points that includes:
    - Combined overview of both papers
    - Similarities and differences
    - Extracted reference list (with author names and publication years)
  agent: DataExtractor

review_task:
  description: >
    Using the structured alignment provided by the DataExtractor, write a complete and in-depth review of the two research papers.

    Your review should:
    - Provide a brief introduction to the topics covered by both papers
    - Compare and contrast the findings, methodologies, and conclusions
    - Discuss any contradictions, gaps, or future research implications
    - Mention references from both papers in-text where applicable
    - Conclude with a strong synthesis and closing thoughts

    Format the output as a cohesive academic-style review with a reference section at the end.
  expected_output: >
    A comprehensive review in essay format (approx. 700–1200 words), complete with:
    - Clear structure (introduction, comparison, conclusion)
    - In-text references
    - Final references section
  agent: reviewer


chat_task:
  description: >
    Respond to {question} by analyzing the full review and relevant extracted information.
    Ensure the answers are coherent, well-structured, and reference specific parts of the source material.
  expected_output: >
    A thoughtful and detailed response that directly addresses the user’s question, 
    includes references to relevant sections of the review, and highlights key findings or insights 
    drawn from the extracted data.
  agent: ReviewChatBot
  quality_criteria:
    - Relevance: The answer must clearly relate to the user's question.
    - Traceability: Reference specific parts of the review or data.
    - Clarity: Use simple and professional language suitable for academic or technical readers.
    - Structure: Format the answer using headings, bullet points, or short paragraphs if needed.